version: "3.7"
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: d3-chart
    ports:
      - 27017:27017
    volumes:
      - mongodb-data-volume:/data/db
    networks: 
      - mongodb-data-network

volumes:
  mongodb-data-volume:

networks: 
  mongodb-data-network:
